// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmniSight.Data;

#nullable disable

namespace OmniSight.Data.Migrations
{
    [DbContext(typeof(OmniSightDbContext))]
    [Migration("20260418135516_CleanVietnameseDB")]
    partial class CleanVietnameseDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmniSight.Core.Entities.Assignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBaiTap");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<string>("AttachmentUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LinkDinhKem");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiTao");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MoTa");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("HanNop");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("ClassId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UserId");

                    b.ToTable("BaiTap");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.AuthToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaToken");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayHetHan");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("DaSuDung");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ChuoiToken");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("LoaiToken");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TokenXacThuc");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenLop");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaThamGia");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("MaMonHoc");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("MaGiaoVien");

                    b.HasKey("ClassId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ClassMember", b =>
                {
                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("MaHocSinh");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayThamGia");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClassId", "StudentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("ThanhVienLop");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Exam", b =>
                {
                    b.Property<int>("ExamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDeThi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExamId"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("ThoiGianLamBai");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianDongDe");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianMoDe");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TieuDe");

                    b.HasKey("ExamId");

                    b.HasIndex("ClassId");

                    b.ToTable("DeThi");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ExamResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKetQua");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("AnswersData")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuLieuDapAn");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianKetThuc");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("MaDeThi");

                    b.Property<string>("RetakeStatus")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThaiLamLai");

                    b.Property<float?>("Score")
                        .HasColumnType("real")
                        .HasColumnName("DiemSo");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianBatDau");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("MaHocSinh");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("KetQuaThi");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCauHoi");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<string>("CorrectOption")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("DapAnDung");

                    b.Property<int>("ExamId")
                        .HasColumnType("int")
                        .HasColumnName("MaDeThi");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DapAnA");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DapAnB");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DapAnC");

                    b.Property<string>("OptionD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DapAnD");

                    b.HasKey("QuestionId");

                    b.HasIndex("ExamId");

                    b.ToTable("CauHoi");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Stream", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBaiDang");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDang");

                    b.Property<int>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("MaLop");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NoiDung");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayTao");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ClassId");

                    b.HasIndex("UserId");

                    b.ToTable("BangTin");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaMonHoc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenMonHoc");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("MaGiaoVien");

                    b.HasKey("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaBaiNop");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int")
                        .HasColumnName("MaBaiTap");

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NhanXet");

                    b.Property<string>("FileOrLinkUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("LinkBaiLam");

                    b.Property<float?>("Score")
                        .HasColumnType("real")
                        .HasColumnName("DiemSo");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("MaHocSinh");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayNop");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SubmissionId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("UserId");

                    b.ToTable("BaiNop");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaNguoiDung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AnhDaiDien");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Email");

                    b.Property<string>("FaceEmbedding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DuLieuKhuonMat");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("HoTen");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("MaGoogle");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("DaXacNhanEmail");

                    b.Property<bool>("IsStudent")
                        .HasColumnType("bit")
                        .HasColumnName("LaHocSinh");

                    b.Property<bool>("IsTeacher")
                        .HasColumnType("bit")
                        .HasColumnName("LaGiaoVien");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("MatKhau");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SoDienThoai");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenDangNhap");

                    b.HasKey("UserId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ViolationLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaViPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("AnhViPham");

                    b.Property<int>("ResultId")
                        .HasColumnType("int")
                        .HasColumnName("MaKetQua");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TrangThai");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("ThoiGianViPham");

                    b.Property<string>("ViolationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LoaiViPham");

                    b.HasKey("LogId");

                    b.HasIndex("ResultId");

                    b.ToTable("NhatKyViPham");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Assignment", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", null)
                        .WithMany("AssignmentsCreated")
                        .HasForeignKey("UserId");

                    b.Navigation("Class");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.AuthToken", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Class", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Subject", "Subject")
                        .WithMany("Classes")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", "Teacher")
                        .WithMany("TeachingClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ClassMember", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Class", "Class")
                        .WithMany("ClassMembers")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", null)
                        .WithMany("ClassMemberships")
                        .HasForeignKey("UserId");

                    b.Navigation("Class");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Exam", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Class", "Class")
                        .WithMany("Exams")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ExamResult", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Exam", "Exam")
                        .WithMany("ExamResults")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", null)
                        .WithMany("ExamResults")
                        .HasForeignKey("UserId");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Question", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Stream", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.Class", "Class")
                        .WithMany("Streams")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", null)
                        .WithMany("Streams")
                        .HasForeignKey("UserId");

                    b.Navigation("Author");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Subject", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Submission", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.Assignment", "Assignment")
                        .WithMany("Submissions")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("OmniSight.Core.Entities.User", null)
                        .WithMany("Submissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ViolationLog", b =>
                {
                    b.HasOne("OmniSight.Core.Entities.ExamResult", "ExamResult")
                        .WithMany("ViolationLogs")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ExamResult");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Assignment", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ClassMembers");

                    b.Navigation("Exams");

                    b.Navigation("Streams");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Exam", b =>
                {
                    b.Navigation("ExamResults");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.ExamResult", b =>
                {
                    b.Navigation("ViolationLogs");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.Subject", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("OmniSight.Core.Entities.User", b =>
                {
                    b.Navigation("AssignmentsCreated");

                    b.Navigation("ClassMemberships");

                    b.Navigation("ExamResults");

                    b.Navigation("Streams");

                    b.Navigation("Submissions");

                    b.Navigation("TeachingClasses");
                });
#pragma warning restore 612, 618
        }
    }
}
